"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CUSTOM_PATH = exports.POLL_THRESHOLD = exports.POLL_INTERVAL = exports.TRIGGER = exports.EXECUTE = exports.ISACTIVE = exports.COMMANDS = exports.MACROS = exports.SCENARIOS = exports.RECIPES = exports.DEVICES = exports.INFO = exports.ROOMS = exports.API_BASE_URL = void 0;
exports.API_BASE_URL = 'v1/projects/home';
exports.ROOMS = 'rooms';
exports.INFO = 'info';
exports.DEVICES = 'devices';
exports.RECIPES = 'recipes';
exports.SCENARIOS = 'scenarios';
exports.MACROS = 'macros';
exports.COMMANDS = 'commands';
exports.ISACTIVE = 'isactive';
exports.EXECUTE = 'execute';
exports.TRIGGER = 'trigger';
exports.POLL_INTERVAL = 60;
exports.POLL_THRESHOLD = 15;
exports.CUSTOM_PATH = '0_userdata.0.neeo';
